package edu.one.core.test.load

import io.gatling.core.Predef._
import io.gatling.core.session.Expression
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._
import io.gatling.http.Headers.Names._
import io.gatling.http.Headers.Values._
import scala.concurrent.duration._
import bootstrap._
import assertions._
import java.net.URLEncoder

class ConfigureAccountSimulation extends Simulation {

  val httpProtocol = http
    .baseURL("http://one")
    .disableFollowRedirect
    .acceptHeader("image/png,image/*;q=0.8,*/*;q=0.5")
    .acceptEncodingHeader("gzip, deflate")
    .acceptLanguageHeader("fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3")
    .userAgentHeader("Mozilla/5.0 (X11; Linux i686; rv:17.0) Gecko/20131030 Firefox/17.0 Iceweasel/17.0.10")
    .disableFollowRedirect

  val headers_1 = Map("""Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_3 = Map(
    """Accept""" -> """*/*""")

  val headers_5 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_6 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_15 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""",
    """Cache-Control""" -> """no-cache""",
    """Content-Type""" -> """text/plain""",
    """Pragma""" -> """no-cache""")

  val headers_16 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""",
    """Cache-Control""" -> """no-cache""",
    """Pragma""" -> """no-cache""")

  val headers_17 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""",
    """Content-Type""" -> """application/x-www-form-urlencoded""")

  val headers_27 = Map(
    """Accept""" -> """*/*""")

  val headers_28 = Map("""Accept""" -> """*/*""")

  val headers_36 = Map(
    """Accept""" -> """*/*""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_37 = Map(
    """Accept""" -> """application/json, text/plain, */*""")

  val headers_39 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_40 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_41 = Map(
    """Accept""" -> """application/json, text/javascript, */*; q=0.01""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_44 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_47 = Map("""Accept""" -> """application/json, text/plain, */*""")

  val headers_56 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_76 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_125 = Map(
    """Accept""" -> """*/*""",
    """Cache-Control""" -> """no-cache""",
    """Content-Type""" -> """multipart/form-data; boundary=---------------------------11742203012065820070811547191""",
    """Pragma""" -> """no-cache""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val chain_0 = exec(http("get root page")
    .get("""/""")
    .headers(headers_1)
    .check(status.is(302)))
    .pause(55 milliseconds)
    .exec(http("get login page")
    .get("""/auth/login?callback=http://one/""")
    .headers(headers_1))
    .pause(66 milliseconds)
    .exec(http("request_3")
    .get("""/auth/public/js/auth.js""")
    .headers(headers_3)
    )
    .exec(http("request_4")
    .get("""/auth/public/img/auth.png""")
    )
    .exec(http("request_5")
    .get("""/auth/public/css/auth.css""")
    .headers(headers_5)
    )
    .pause(50 milliseconds)
    .exec(http("request_6")
    .get("""/auth/public/fonts/KGJuneBug.ttf""")
    .headers(headers_6)
    )
    .exec(http("request_7")
    .get("""/auth/public/img/illustrations/logo.png""")
    )
    .pause(24 milliseconds)
    .exec(http("request_8")
    .get("""/favicon.ico""")
    .headers(headers_1)
    .check(status.is(404)))
    .pause(1)
    .exec(http("get activation page")
    .get("""/auth/activation""")
    .headers(headers_1))
    .pause(19 milliseconds)
    .exec(http("request_10")
    .get("""/auth/public/css/auth.css""")
    .headers(headers_5)
    )
    .exec(http("request_11")
    .get("""/auth/public/js/auth.js""")
    .headers(headers_3)
    )
    .exec(http("request_12")
    .get("""/auth/public/img/auth.png""")
    )
    .pause(34 milliseconds)
    .exec(http("request_13")
    .get("""/auth/public/fonts/KGJuneBug.ttf""")
    .headers(headers_6)
    )
    .exec(http("request_14")
    .get("""/auth/public/img/illustrations/logo.png""")
    )
    .pause(16)
    .feed(ssv("activation_de_comptes.csv"))
    .exec(http("post activation")
    .post("""/auth/activation""")
    .headers(headers_17)
    .param("""login""", """${login}""")
    .param("""activationCode""", """${code}""")
    .param("""password""", """${code}${code}""")
    .param("""confirmPassword""", """${code}${code}""")
    .check(status.is(302)))
    .pause(31 milliseconds)
    .exec(http("get login page")
    .get("""/auth/login""")
    .headers(headers_1))
    .pause(22 milliseconds)
    .exec(http("request_19")
    .get("""/auth/public/js/auth.js""")
    .headers(headers_3)
    )
    .exec(http("request_20")
    .get("""/auth/public/css/auth.css""")
    .headers(headers_5)
    )
    .pause(19 milliseconds)
    .exec(http("request_21")
    .get("""/auth/public/img/auth.png""")
    )
    .pause(17 milliseconds)
    .exec(http("request_22")
    .get("""/auth/public/img/illustrations/logo.png""")
    )
    .exec(http("request_23")
    .get("""/auth/public/fonts/KGJuneBug.ttf""")
    .headers(headers_6)
    )
    .pause(9)
    .exec(http("log user")
    .post("""/auth/login""")
    .headers(headers_17)
    .param("""callBack""", """""")
    .param("""email""", """${login}""")
    .param("""password""", """${code}${code}""")
    .check(status.is(302)))
    .pause(12 milliseconds)
    .exec(http("get root page (authenticated)")
    .get("""/""")
    .headers(headers_1))
    .pause(32 milliseconds)
    .exec(http("get timeline page")
    .get("""/timeline/timeline""")
    .headers(headers_1))
    .pause(34 milliseconds)
    .exec(http("request_27")
    .get("""/infra/public/js/one-loader.js""")
    .headers(headers_27)
    )
    .exec(http("request_28")
    .get("""/timeline/public/js/timeline.js""")
    .headers(headers_28))
    .pause(17 milliseconds)
    .exec(http("request_29")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .headers(headers_27)
    )
    .exec(http("request_30")
    .get("""/infra/public/js/one.js""")
    .headers(headers_27)
    )
    .exec(http("request_31")
    .get("""/infra/public/js/angular.min.js""")
    .headers(headers_27)
    )
    .exec(http("request_32")
    .get("""/infra/public/js/humane.min.js""")
    .headers(headers_27)
    )
    .exec(http("request_33")
    .get("""/infra/public/js/ui.js""")
    .headers(headers_27)
    )
    .exec(http("request_34")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .headers(headers_27)
    )
    .pause(11 milliseconds)
    .exec(http("request_35")
    .get("""/infra/public/js/one-app.js""")
    .headers(headers_27)
    )
    .pause(106 milliseconds)
    .exec(http("get timeline i18n")
    .get("""/timeline/i18n""")
    .headers(headers_36))
    .pause(103 milliseconds)
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_37)
    )
    .exec(http("get user infos json")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_36))
    .pause(38 milliseconds)
    .exec(http("request_39")
    .get("""/infra/public/js/underscore-min-1.4.4.js""")
    .headers(headers_39)
    )
    .exec(http("request_40")
    .get("""/infra/public/css/original.css""")
    .headers(headers_40)
    )
    .pause(18 milliseconds)
    .exec(http("get user theme json")
    .get("""/theme?token=0.09460127975163801""")
    .headers(headers_41))
    .exec(http("get widgets json")
    .get("""/timeline/public/json/widgets.json?_=1384351374774""")
    .headers(headers_36))
    .pause(16 milliseconds)
    .exec(http("get userbook user infos json")
    .get("""/userbook/api/person?_=1384351374773""")
    .headers(headers_36))
    .exec(http("request_44")
    .get("""/assets/themes/panda/default/theme.css""")
    .headers(headers_44)
    )
    .exec(http("request_45")
    .get("""/infra/public/js/moment+langs.js""")
    .headers(headers_39)
    )
    .pause(25 milliseconds)
    .exec(http("request_46")
    .get("""/directory/public/js/birthday.js""")
    .headers(headers_28))
    .exec(http("get calendar widget page")
    .get("""/timeline/calendar""")
    .headers(headers_47))
    .pause(11 milliseconds)
    .exec(http("request_48")
    .get("""/timeline/public/js/calendar.js""")
    .headers(headers_28))
    .exec(http("get birthday widget page")
    .get("""/userbook/birthday""")
    .headers(headers_47))
    .pause(12 milliseconds)
    .exec(http("get default avatar img")
    .get("""/userbook/document/no-avatar.jpg?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48"""))
    .pause(168 milliseconds)
    .exec(http("request_51")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    )
    .exec(http("request_52")
    .get("""/assets/themes/panda/img/icons/tools.png""")
    )
    .exec(http("request_53")
    .get("""/assets/themes/panda/img/icons/user.png""")
    )
    .exec(http("request_54")
    .get("""/assets/themes/panda/img/icons/notification.png""")
    )
    .exec(http("request_55")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    )
    .pause(13 milliseconds)
    .exec(http("request_56")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_56)
    )
    .exec(http("get availables themes json")
    .get("""/timeline/public/json/themes.json?_=1384351374778""")
    .headers(headers_36))
    .exec(http("timeline : list types json")
    .get("""/timeline/types?_=1384351374775""")
    .headers(headers_36))
    .pause(18 milliseconds)
    .exec(http("get user infos json")
    .get("""/auth/oauth2/userinfo?_=1384351374776""")
    .headers(headers_36))
    .pause(15 milliseconds)
    .exec(http("request_60")
    .get("""/assets/themes/panda/img/illustrations/calendar-header.png""")
    )
    .exec(http("request_61")
    .get("""/assets/themes/panda/img/illustrations/calendar-separator.png""")
    )
    .exec(http("timeline lastNotifications json")
    .get("""/timeline/lastNotifications?_=1384351374777""")
    .headers(headers_36)
    .check(status.is(200), jsonPath("status").is("ok"),
      jsonPath("$.results..sender").findAll.saveAs("senders")))
    .pause(18 milliseconds)
    .exec(http("request_63")
    .get("""/assets/themes/panda/img/illustrations/birthdays-header-fr.png""")
    )
    .pause(17 milliseconds)
    .exec(http("list visibles bithday for three currents month")
    .get("""/userbook/person/birthday?_=1384351374779""")
    .headers(headers_36)
    .check(status.is(200),
      jsonPath("$..id").findAll.saveAs("birthdayUsers")))
    .pause(30 milliseconds)
    .exec(http("request_65")
    .get("""/assets/themes/panda/desert/thumbnail.png""")
    )

  val chain_1 = exec(http("request_66")
    .get("""/assets/themes/panda/hills/thumbnail.png""")
    )
    .exec(http("request_67")
    .get("""/assets/themes/panda/panda-food/thumbnail.png""")
    )
    .exec(http("request_68")
    .get("""/assets/themes/panda/default/thumbnail.png""")
    )
    .exec(http("request_69")
    .get("""/assets/themes/panda/sparkly/thumbnail.png""")
    )
    .exec(http("request_70")
    .get("""/assets/themes/panda/eliot/thumbnail.png""")
    )
    .pause(157 milliseconds)
    .exec(http("request_71")
    .get("""/assets/themes/panda/img/icons/blog.png""")
    )
    .exec(http("request_72")
    .get("""/assets/themes/panda/img/icons/share.png""")
    )
    .pause(120 milliseconds)
    .foreach("${senders}", "senderId") {
      exec(http("get timeline event avatar")
        .get("""/userbook/avatar/${senderId}?thumbnail=82x82""")
        .check(status.in(Seq(200, 301)), header("Location").find.transform(_.orElse(Some(""))).saveAs("avatarUser")))
        .pause(12 milliseconds)
        .doIf(session => session("avatarUser").asOption.getOrElse("") != "") {
          exec(http("get timeline event avatar (after redirect)")
            .get("""${avatarUser}""")
            .headers(headers_76)
          )
        }
    }
    .foreach("${birthdayUsers}", "bUserId") {
      exec(http("get birthday avatar")
        .get("""/userbook/avatar/${bUserId}?thumbnail=48x48""")
        .check(status.in(Seq(200, 301)), header("Location").find.transform(_.orElse(Some(""))).saveAs("avatarUser")))
        .pause(12 milliseconds)
        .doIf(session => session("avatarUser").asOption[String].getOrElse("") != "") {
          exec(http("get birthday avatar (after redirect)")
            .get("""${avatarUser}""")
            .headers(headers_76)
//            .check(status.in(Seq(200, 401)).saveAs("statusImg"))
          )
//          .exec{session =>
//            val statusImg = session("statusImg").asOption[Int].getOrElse(401)
//            if (statusImg == 401) {
//              println("url : " + session("avatarUser").as[String] + " - " + statusImg)
//            }
//            session
//          }
        }
    }
    .exec(http("get account page")
    .get("""/userbook/mon-compte""")
    .headers(headers_1))
    .pause(29 milliseconds)
    .exec(http("request_80")
    .get("""/directory/public/js/account.js""")
    .headers(headers_28))
    .exec(http("request_81")
    .get("""/infra/public/js/one-loader.js""")
    .headers(headers_27)
    )
    .pause(27 milliseconds)
    .exec(http("request_82")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .headers(headers_27)
    )
    .exec(http("request_83")
    .get("""/infra/public/js/ui.js""")
    .headers(headers_27)
    )
    .exec(http("request_84")
    .get("""/infra/public/js/one-app.js""")
    .headers(headers_27)
    )
    .exec(http("request_85")
    .get("""/infra/public/js/humane.min.js""")
    .headers(headers_27)
    )
    .exec(http("request_86")
    .get("""/infra/public/js/angular.min.js""")
    .headers(headers_27)
    )
    .pause(12 milliseconds)
    .exec(http("request_87")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .headers(headers_27)
    )
    .exec(http("request_88")
    .get("""/infra/public/js/one.js""")
    .headers(headers_27)
    )
    .pause(130 milliseconds)
    .exec(http("get directory i18n")
    .get("""/directory/i18n""")
    .headers(headers_36))
    .pause(103 milliseconds)
    .exec(http("get user infos json")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_36))
    .exec(http("request_91")
    .get("""/infra/public/js/moment+langs.js""")
    .headers(headers_39)
    )
    .pause(41 milliseconds)
    .exec(http("request_92")
    .get("""/infra/public/js/underscore-min-1.4.4.js""")
    .headers(headers_39)
    )
    .pause(42 milliseconds)
    .exec(http("get reset password page")
    .get("""/auth/reset/password""")
    .headers(headers_47))
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_37)
    )
    .pause(30 milliseconds)
    .exec(http("get userbook infos json")
    .get("""/userbook/api/person?_=1384351383490""")
    .headers(headers_36))
    .pause(119 milliseconds)
    .exec(http("request_96")
    .get("""/infra/public/css/original.css""")
    .headers(headers_40)
    )
    .pause(37 milliseconds)
    .exec(http("get user theme")
    .get("""/theme?token=0.496901165503141""")
    .headers(headers_41))
    .pause(14 milliseconds)
    .exec(http("get userbook infos json")
    .get("""/userbook/api/person?_=1384351383491""")
    .headers(headers_36))
    .exec(http("request_99")
    .get("""/assets/themes/panda/default/theme.css""")
    .headers(headers_44)
    )
    .pause(13 milliseconds)
    .exec(http("request_100")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48"""))
    .pause(23 milliseconds)
    .exec(http("request_101")
    .get("""/userbook/document/no-avatar.jpg?userbook-dimg=public/img/no-avatar.jpg&v=0&thumbnail=290x290"""))
    .exec(http("request_102")
    .get("""/userbook/document/no-avatar.jpg?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48"""))
    .pause(61 milliseconds)
    .exec(http("request_103")
    .get("""/assets/themes/panda/img/icons/user.png""")
    )
    .exec(http("request_104")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    )
    .exec(http("request_105")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    )
    .exec(http("request_106")
    .get("""/assets/themes/panda/img/icons/orange-user.png""")
    )
    .pause(11 milliseconds)
    .exec(http("request_107")
    .get("""/assets/themes/panda/img/icons/default-panda-60px.png""")
    )
    .exec(http("request_108")
    .get("""/assets/themes/panda/img/icons/public.png""")
    )
    .exec(http("request_109")
    .get("""/assets/themes/panda/img/icons/arrow-bottom.png""")
    )
    .exec(http("request_110")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_56)
    )
    .pause(14)
    .exec(http("change email")
    .get("""/userbook/api/edit-user-info?prop=email&value=${login}@one1d.fr&_=1384351383492""")
    .headers(headers_36))
    .pause(489 milliseconds)
    .feed(ssv("citations.csv").circular)
    .exec{session =>
      session.set("encodedCitation", URLEncoder.encode(
        session("citation").as[String] + " - " + session("author").as[String], "UTF-8"))
    }
    .exec(http("change motto")
    .get("""/userbook/api/edit-userbook-info?prop=motto&value=${encodedCitation}&_=1384351383493""")
    .headers(headers_36))
    .pause(933 milliseconds)
    .exec(http("request_113")
    .get("""/assets/themes/panda/img/icons/happy-panda.png""")
    )
    .exec(http("request_114")
    .get("""/assets/themes/panda/img/icons/proud-panda.png""")
    )
    .exec(http("request_115")
    .get("""/assets/themes/panda/img/icons/love-panda.png""")
    )
    .exec(http("request_116")
    .get("""/assets/themes/panda/img/icons/angry-panda.png""")
    )
    .exec(http("request_117")
    .get("""/assets/themes/panda/img/icons/tired-panda.png""")
    )
    .exec(http("request_118")
    .get("""/assets/themes/panda/img/icons/worried-panda.png""")
    )
    .pause(12 milliseconds)
    .exec(http("request_119")
    .get("""/assets/themes/panda/img/icons/dreamy-panda.png""")
    )
    .exec(http("request_120")
    .get("""/assets/themes/panda/img/icons/sick-panda.png""")
    )
    .exec(http("request_121")
    .get("""/assets/themes/panda/img/icons/sad-panda.png""")
    )
    .exec(http("request_122")
    .get("""/assets/themes/panda/img/icons/joker-panda.png""")
    )
    .pause(1)
    .exec(http("change mood")
    .get("""/userbook/api/edit-userbook-info?prop=mood&value=happy&_=1384351383494""")
    .headers(headers_36))
    .pause(8)
    .exec(http("request_124")
    .get("""/assets/themes/panda/img/illustrations/loading.gif""")
    )
    .pause(179 milliseconds)
    .exec(http("upload avatar")
    .post("""/workspace/document?application=userbook&protected=true&thumbnail=290x290&thumbnail=82x82&thumbnail=48x48""")
    .headers(headers_125)
    .body(RawFileBody("ConfigureAccountSimulation_request_125.txt"))
    .check(status.is(201), jsonPath("$._id").find.saveAs("avatar")))
    .pause(139 milliseconds)
    .exec(http("change avatar")
    .get("""/userbook/api/edit-userbook-info?prop=picture&value=${avatar}&_=1384351383495""")
    .headers(headers_36))
    .pause(17 milliseconds)
    .exec(http("get userbook infos json")
    .get("""/userbook/api/person?_=1384351383496""")
    .headers(headers_36))
    .pause(23 milliseconds)
    .exec(http("get new avatar 290 img")
    .get("""/userbook/document/${avatar}?userbook-dimg=public/img/no-avatar.jpg&v=0&thumbnail=290x290"""))
    .pause(87 milliseconds)
    .exec(http("get new avatar 48 img")
    .get("""/userbook/document/${avatar}?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48"""))
    .pause(6)
    .exec(http("change sport hobby")
    .get("""/userbook/api/edit-userbook-info?category=sport&values=d&visibility=public&$$hashKey=00C&_=1384351383497""")
    .headers(headers_36))
    .pause(866 milliseconds)

  val chain_2 = exec(http("change cinema hobby")
    .get("""/userbook/api/edit-userbook-info?category=cinema&values=d&visibility=public&$$hashKey=00D&_=1384351383498""")
    .headers(headers_36))
    .pause(2)
    .exec(http("change animals hobby")
    .get("""/userbook/api/edit-userbook-info?category=animals&values=a&visibility=public&$$hashKey=00E&_=1384351383499""")
    .headers(headers_36))
    .pause(1)
    .exec(http("change music hobby")
    .get("""/userbook/api/edit-userbook-info?category=music&values=g&visibility=public&$$hashKey=00F&_=1384351383500""")
    .headers(headers_36))
    .pause(1)
    .exec(http("change places hobby")
    .get("""/userbook/api/edit-userbook-info?category=places&values=s&visibility=public&$$hashKey=00G&_=1384351383501""")
    .headers(headers_36))
    .pause(2)
    .exec(http("request_135")
    .get("""/assets/themes/panda/img/icons/prive.png""")
    )
    .exec(http("change visibility of animals hobby")
    .get("""/userbook/api/set-visibility?value=PRIVE&category=animals&_=1384351383502""")
    .headers(headers_36))
    .pause(1)
    .exec(http("change health property")
    .get("""/userbook/api/edit-userbook-info?prop=health&value=r&_=1384351383503""")
    .headers(headers_36))
    .pause(7)
    .exec(http("logout")
    .get("""/auth/logout?callback=""")
    .headers(headers_1)
    .check(status.is(302)))
    .exec(http("get root page")
    .get("""/""")
    .headers(headers_1)
    .check(status.is(302)))
    .pause(15 milliseconds)
    .exec(http("get login page")
    .get("""/auth/login?callback=http://one/""")
    .headers(headers_1))
    .pause(17 milliseconds)
    .exec(http("request_183")
    .get("""/auth/public/css/auth.css""")
    .headers(headers_5)
    )
    .exec(http("request_184")
    .get("""/auth/public/js/auth.js""")
    .headers(headers_3)
    )
    .pause(12 milliseconds)
    .exec(http("request_185")
    .get("""/auth/public/img/auth.png""")
    )
    .pause(20 milliseconds)
    .exec(http("request_186")
    .get("""/auth/public/img/illustrations/logo.png""")
    )
    .exec(http("request_187")
    .get("""/auth/public/fonts/KGJuneBug.ttf""")
    .headers(headers_6)
    )

  val scn = scenario("Active and configure account").exec(
    chain_0, chain_1, chain_2)

  setUp(scn.inject(ramp(9 users) over (10 seconds))).protocols(httpProtocol)
}
