GRANT USAGE ON SCHEMA flashmsg TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA flashmsg TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA flashmsg TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA flashmsg TO "apps";