GRANT USAGE ON SCHEMA conversation TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA conversation TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA conversation TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA conversation TO "apps";