package org.entcore.test.load

import io.gatling.http.Predef._
import io.gatling.core.Predef._
import bootstrap._
import java.net.URLEncoder
import net.minidev.json.{JSONObject, JSONValue}
import scala.concurrent.duration._
import scala.collection.JavaConverters._

object StudentScenario {

  val headers_1 = Map("""Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_4 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_5 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_7 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_8 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""",
    """Content-Type""" -> """application/x-www-form-urlencoded""")

  val headers_20 = Map("""X-Requested-With""" -> """XMLHttpRequest""")

  val headers_22 = Map(
    """Accept""" -> """application/json, text/plain, */*""")

  val headers_23 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_24 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_26 = Map(
    """Accept""" -> """application/json, text/javascript, */*; q=0.01""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_30 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_35 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_37 = Map("""Accept""" -> """application/json, text/plain, */*""")

  val headers_38 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_45 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_46 = Map("""Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_99 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_109 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_119 = Map(
    """Accept""" -> """application/json, text/plain, */*""")

  val headers_120 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_123 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_125 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_131 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_133 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_146 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_159 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_160 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_178 = Map("""Accept""" -> """text/css,*/*;q=0.1""")

  val headers_186 = Map(
    """Cache-Control""" -> """no-cache""",
    """Content-Type""" -> """multipart/form-data; boundary=---------------------------10797810774189015011942205288""",
    """Pragma""" -> """no-cache""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_188 = Map(
    """Cache-Control""" -> """no-cache""",
    """Content-Type""" -> """application/x-www-form-urlencoded; charset=UTF-8""",
    """Pragma""" -> """no-cache""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_207 = Map(
    """Cache-Control""" -> """no-cache""",
    """Content-Type""" -> """multipart/form-data; boundary=---------------------------1289423945374670221677674784""",
    """Pragma""" -> """no-cache""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_337 = Map(
    """Cache-Control""" -> """no-cache""",
    """Content-Type""" -> """multipart/form-data; boundary=---------------------------157465906117855667891860310867""",
    """Pragma""" -> """no-cache""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_342 = Map(
    """Accept""" -> """application/json, text/plain, */*""")

  val headers_351 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_353 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_354 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val chain_0 = exec(http("get root page")
    .get("""/""")
    .headers(headers_1)
    .check(status.is(302)))
    .pause(90 milliseconds)
    .exec(http("get  login page")
    .get("""/auth/login?callback=http://one/""")
    .headers(headers_1))
    .pause(71 milliseconds)
    .exec(http("auth.js")
    .get("""/auth/public/js/auth.js"""))
    .exec(http("auth.css")
    .get("""/auth/public/css/auth.css""")
    .headers(headers_4))
    .exec(http("auth.png")
    .get("""/auth/public/img/auth.png""")
    .headers(headers_5))
    .pause(33 milliseconds)
    .exec(http("logo.png")
    .get("""/current/assets/img/illustrations/logo.png""")
    .headers(headers_5))
    .pause(40 milliseconds)
    .exec(http("KGJuneBug.ttf")
    .get("""/auth/public/fonts/KGJuneBug.ttf""")
    .headers(headers_7))
    .pause(7)
    .feed(ssv("students.csv"))
    .exec(http("log user")
    .post("""/auth/login""")
    .headers(headers_8)
    .param("""email""", """${login}""")
    .param("""password""", """${code}${code}""")
    .check(status.is(302)))
    .pause(76 milliseconds)
    .exec(http("get root page (authenticated)")
    .get("""/""")
    .headers(headers_1))
    .pause(67 milliseconds)
    .exec(http("get timeline page")
    .get("""/timeline/timeline""")
    .headers(headers_1))
    .pause(21 milliseconds)
    .exec(http("timeline.js")
    .get("""/timeline/public/js/timeline.js"""))
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js"""))
    .pause(61 milliseconds)
    .exec(http("one.js")
    .get("""/infra/public/js/one.js"""))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js"""))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js"""))
    .pause(13 milliseconds)
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js"""))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js"""))
    .pause(11 milliseconds)
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js"""))
    .pause(48 milliseconds)
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js"""))
    .pause(136 milliseconds)
    .exec(http("get timeline i18n")
    .get("""/timeline/i18n""")
    .headers(headers_20))
    .pause(68 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("get portal page")
    .get("""/public/template/portal.html""")
    .headers(headers_22))
    .pause(42 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_23))
    .exec(http("underscore-min-1.4.4.js")
    .get("""/infra/public/js/underscore-min-1.4.4.js""")
    .headers(headers_24))
    .pause(36 milliseconds)
    .exec(http("get widgets json")
    .get("""/timeline/public/json/widgets.json?_=1384422780883""")
    .headers(headers_20))
    .exec(http("get user theme")
    .get("""/theme?token=0.46356402737929747""")
    .headers(headers_26))
    .pause(20 milliseconds)
    .exec(http("moment+langs.js")
    .get("""/infra/public/js/moment+langs.js""")
    .headers(headers_24))
    .exec(http("calendar.js")
    .get("""/timeline/public/js/calendar.js"""))
    .pause(30 milliseconds)
    .exec(http("birthday.js")
    .get("""/directory/public/js/birthday.js"""))
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_30))
    .pause(44 milliseconds)
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384422780882""")
    .headers(headers_20))
    .pause(78 milliseconds)
    .exec(http("get availables themes json")
    .get("""/timeline/public/json/themes.json?_=1384422780888""")
    .headers(headers_20))
    .pause(11 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo?_=1384422780886""")
    .headers(headers_20))
    .pause(15 milliseconds)
    .exec(http("get timeline types")
    .get("""/timeline/types?_=1384422780885""")
    .headers(headers_20))
    .pause(35 milliseconds)
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_35))
    .pause(65 milliseconds)
    .exec(http("get birthdays")
    .get("""/userbook/person/birthday?_=1384422780884""")
    .headers(headers_20)
    .check(status.is(200),
    jsonPath("$..id").findAll.saveAs("birthdayUsers")))
    .exec(http("get birthday page")
    .get("""/userbook/birthday""")
    .headers(headers_37))
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_38))
    .pause(337 milliseconds)
    .exec(http("get calendar page")
    .get("""/timeline/calendar""")
    .headers(headers_37))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_35))
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_35))
    .exec(http("tools.png")
    .get("""/assets/themes/panda/img/icons/tools.png""")
    .headers(headers_35))
    .exec(http("notification.png")
    .get("""/assets/themes/panda/img/icons/notification.png""")
    .headers(headers_35))
    .exec(http("get timeline events")
    .get("""/timeline/lastNotifications?_=1384422780887""")
    .headers(headers_20)
    .check(status.is(200), jsonPath("status").is("ok"),
    jsonPath("$.results..sender").findAll.transform(_.orElse(Some(Nil))).saveAs("senders")))
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_45))
    .pause(67 milliseconds)
    .foreach("${birthdayUsers}", "bUserId") {
    exec(http("get birthday avatar")
      .get("""/userbook/avatar/${bUserId}?thumbnail=48x48""")
      .check(status.in(Seq(200, 301)), header("Location").find.transform(_.orElse(Some(""))).saveAs("avatarUser")))
      .pause(12 milliseconds)
      .doIf(session => session("avatarUser").asOption[String].getOrElse("") != "") {
      exec(http("get birthday avatar (after redirect)")
        .get("""${avatarUser}""")
        .headers(headers_46)
      )
    }
  }
    .pause(13 milliseconds)
    .exec(http("default/thumbnail.png")
    .get("""/assets/themes/panda/default/thumbnail.png""")
    .headers(headers_35))
    .exec(http("hills/thumbnail.png")
    .get("""/assets/themes/panda/hills/thumbnail.png""")
    .headers(headers_35))
    .pause(21 milliseconds)
    .exec(http("desert/thumbnail.png")
    .get("""/assets/themes/panda/desert/thumbnail.png""")
    .headers(headers_35))
    .exec(http("panda-food/thumbnail.png")
    .get("""/assets/themes/panda/panda-food/thumbnail.png""")
    .headers(headers_35))
    .pause(66 milliseconds)
    .exec(http("sparkly/thumbnail.png")
    .get("""/assets/themes/panda/sparkly/thumbnail.png""")
    .headers(headers_35))
    .pause(11 milliseconds)

  val chain_1 = exec(http("birthdays-header-fr.png")
    .get("""/assets/themes/panda/img/illustrations/birthdays-header-fr.png""")
    .headers(headers_35))
    .exec(http("share.png")
    .get("""/assets/themes/panda/img/icons/share.png""")
    .headers(headers_35))
    .exec(http("blog.png")
    .get("""/assets/themes/panda/img/icons/blog.png""")
    .headers(headers_35))
    .pause(118 milliseconds)
    .foreach("${senders}", "senderId") {
    exec(http("get timeline event avatar")
      .get("""/userbook/avatar/${senderId}?thumbnail=82x82""")
      .check(status.in(Seq(200, 301)), header("Location").find.transform(_.orElse(Some(""))).saveAs("avatarUser")))
      .pause(12 milliseconds)
      .doIf(session => session("avatarUser").asOption[String].getOrElse("") != "") {
      exec(http("get timeline event avatar (after redirect)")
        .get("""${avatarUser}""")
        .headers(headers_7)
      )
    }
  }
    .exec(http("calendar-header.png")
    .get("""/assets/themes/panda/img/illustrations/calendar-header.png""")
    .headers(headers_35))
    .exec(http("calendar-separator.png")
    .get("""/assets/themes/panda/img/illustrations/calendar-separator.png""")
    .headers(headers_35))
    .pause(27 milliseconds)
    .exec(http("get applications page")
    .get("""/apps""")
    .headers(headers_1))
    .pause(17 milliseconds)
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("app.css")
    .get("""/public/css/app.css""")
    .headers(headers_109))
    .pause(14 milliseconds)
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .pause(12 milliseconds)
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .pause(98 milliseconds)
    .exec(http("get applications i18n")
    .get("""/apps/i18n""")
    .headers(headers_20)
    .check(status.is(404)))
    .pause(46 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .pause(31 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .pause(21 milliseconds)
    .exec(http("get user theme")
    .get("""/theme?token=0.03805585759766428""")
    .headers(headers_26))
    .pause(15 milliseconds)
    .exec(http("empty document avatar")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_46))
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384422792736""")
    .headers(headers_20)
    .check(status.is(200), jsonPath("status").is("ok"),
    jsonPath("$.result.0.photo").find.saveAs("meAvatar")))
    .pause(36 milliseconds)
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("blog-large.png")
    .get("""/assets/themes/panda/img/icons/blog-large.png""")
    .headers(headers_35))
    .pause(12 milliseconds)
    .exec(http("workspace-large.png")
    .get("""/assets/themes/panda/img/icons/workspace-large.png""")
    .headers(headers_35))
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .exec(http("apps.png")
    .get("""/assets/themes/panda/img/icons/apps.png""")
    .headers(headers_35))
    .pause(18 milliseconds)
    .exec(http("get icon avatar")
    .get("""/userbook/document/${meAvatar}?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_133)
    .check(status.in(Seq(200, 304))))
    .pause(3)
    .exec(http("get blog page")
    .get("""/blog""")
    .headers(headers_1))

  val chain_2 = pause(28 milliseconds)
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("blog.js")
    .get("""/blog/public/js/blog.js"""))
    .pause(22 milliseconds)
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one.js")
    .get("""/infra/public/js/one.js""")
    .check(status.in(Seq(200, 304))))
    .pause(97 milliseconds)
    .exec(http("get blog i18n")
    .get("""/blog/i18n""")
    .headers(headers_20))
    .pause(83 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("moment+langs.js")
    .get("""/infra/public/js/moment+langs.js""")
    .headers(headers_146)
    .check(status.in(Seq(200, 304))))
    .pause(30 milliseconds)
    .exec(http("underscore-min-1.4.4.js")
    .get("""/infra/public/js/underscore-min-1.4.4.js""")
    .headers(headers_146)
    .check(status.in(Seq(200, 304))))
    .pause(23 milliseconds)
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo?_=1384422796869""")
    .headers(headers_20))
    .pause(52 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .pause(19 milliseconds)
    .exec(http("empty document avatar")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_46))
    .pause(26 milliseconds)
    .exec(http("list all blogs")
    .get("""/blog/list/all?_=1384422796870""")
    .headers(headers_20)
    .check(status.is(200),
    jsonPath("$.._id").findAll.transform(_.orElse(Some(Nil))).saveAs("blogsIds"),
    jsonPath("$..thumbnail").findAll.transform(_.orElse(Some(Nil))).saveAs("blogsThumbnails")))
    .exec(http("get user theme")
    .get("""/theme?token=0.2530770265949154""")
    .headers(headers_26))
    .pause(13 milliseconds)
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384422796872""")
    .headers(headers_20))
    .exec(http("list all blogs")
    .get("""/blog/list/all?_=1384422796871""")
    .headers(headers_20))
    .pause(71 milliseconds)
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .pause(43 milliseconds)
    .exec(http("get icon avatar")
    .get("""/userbook/document/${meAvatar}?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_133)
    .check(status.in(Seq(200, 304))))
    .exec(http("add.png")
    .get("""/assets/themes/panda/img/icons/add.png""")
    .headers(headers_38))
    .pause(15 milliseconds)
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(95 milliseconds)
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("blog.png")
    .get("""/assets/themes/panda/img/icons/blog.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(58 milliseconds)
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(3)
    .foreach("${blogsThumbnails}", "blogThumb") {
    exec(http("get blog thumbnail")
      .get("""$blogThumb""")
      .headers(headers_46))
      .pause(78 milliseconds)
  }
    .foreach("${blogsIds}", "blogId") { // User read each blog
    exec(http("list posts in blog ${blogId}")
      .get("""/blog/post/list/all/${blogId}?_=1384422796873""")
      .check(status.is(200),
      jsonPath("$.._id").findAll.transform(_.orElse(Some(Nil))).saveAs("postsIds")))  // TODO parse content in first post to find images
      .pause(42 milliseconds)
      .doIf(session => session("postsIds").asOption[List[String]].getOrElse(Nil) != Nil) {
      foreach("${postsIds}", "postId") {
        exec(http("get comments in post ${postId}")
          .get("""/blog/comments/${blogId}/${postId}?_=1384422796875""")
          .headers(headers_20))
          .pause(10)
        feed(ssv("citations.csv").circular)
          .exec{session =>
          session.set("encodedCitation", URLEncoder.encode(
            session("citation").as[String] + " - " + session("author").as[String], "UTF-8"))
        }
          .exec(http("add comment in post ${postId}")
          .post("""/blog/comment/${blogId}/${postId}""")
          .headers(headers_188)
          .param("""comment""", """${encodedCitation}"""))
          .pause(29 milliseconds)
          .exec(http("get comments in post ${postId}")
          .get("""/blog/comments/${blogId}/${postId}?_=1384422796886""")
          .headers(headers_20))
          .pause(9)
      }
    }
      .pause(120) // 2 min to read and comment each post in blog
  }

  val chain_3 = exec(http("get applications page")
    .get("""/apps""")
    .headers(headers_1))
    .pause(15 milliseconds)
    .exec(http("app.css")
    .get("""/public/css/app.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .pause(20 milliseconds)
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one.js")
    .get("""/infra/public/js/one.js""")
    .check(status.in(Seq(200, 304))))
    .pause(109 milliseconds)
    .exec(http("get apps i18n")
    .get("""/apps/i18n""")
    .headers(headers_20)
    .check(status.is(404)))
    .pause(45 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .pause(48 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .pause(12 milliseconds)
    .exec(http("empty document avatar")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_46))
    .exec(http("get user theme")
    .get("""/theme?token=0.3242081556025924""")
    .headers(headers_26))
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384423216724""")
    .headers(headers_20))
    .pause(17 milliseconds)
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .pause(18 milliseconds)
    .exec(http("get icon avatar")
    .get("""/userbook/document/${meAvatar}?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_133)
    .check(status.in(Seq(200, 304))))
    .pause(24 milliseconds)
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("apps.png")
    .get("""/assets/themes/panda/img/icons/apps.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("workspace-large.png")
    .get("""/assets/themes/panda/img/icons/workspace-large.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("blog-large.png")
    .get("""/assets/themes/panda/img/icons/blog-large.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(1)
    .exec(http("get workspace page")
    .get("""/workspace/workspace""")
    .headers(headers_1))
    .pause(15 milliseconds)
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("workspace.js")
    .get("""/workspace/public/js/workspace.js"""))
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .pause(17 milliseconds)
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one.js")
    .get("""/infra/public/js/one.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .pause(134 milliseconds)
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .exec(http("get workspace i18n")
    .get("""/workspace/i18n""")
    .headers(headers_20))
    .pause(39 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("get user theme")
    .get("""/theme?token=0.6614103632515401""")
    .headers(headers_26))
    .pause(25 milliseconds)
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .pause(30 milliseconds)
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))

  val chain_4 = pause(11 milliseconds)
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .pause(6)
    .exec(http("get apps page")
    .get("""/apps""")
    .headers(headers_1))
    .pause(13 milliseconds)
    .exec(http("app.css")
    .get("""/public/css/app.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .pause(16 milliseconds)
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .pause(12 milliseconds)
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .pause(15 milliseconds)
    .exec(http("one.js")
    .get("""/infra/public/js/one.js""")
    .check(status.in(Seq(200, 304))))
    .pause(74 milliseconds)
    .exec(http("get apps i18n")
    .get("""/apps/i18n""")
    .headers(headers_20)
    .check(status.is(404)))
    .pause(50 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .pause(36 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .pause(13 milliseconds)
    .exec(http("empty document avatar")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_46))
    .exec(http("get user theme")
    .get("""/theme?token=0.2172852787006575""")
    .headers(headers_26))
    .pause(14 milliseconds)
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384423225498""")
    .headers(headers_20))
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .pause(32 milliseconds)
    .exec(http("get icon avatar")
    .get("""/userbook/document/${meAvatar}?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_133)
    .check(status.in(Seq(200, 304))))
    .pause(20 milliseconds)
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("workspace-large.png")
    .get("""/assets/themes/panda/img/icons/workspace-large.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(11 milliseconds)
    .exec(http("blog-large.png")
    .get("""/assets/themes/panda/img/icons/blog-large.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("apps.png")
    .get("""/assets/themes/panda/img/icons/apps.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .pause(2)
    .exec(http("get workspace page")
    .get("""/workspace/workspace""")
    .headers(headers_1))
    .pause(13 milliseconds)
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("workspace.js")
    .get("""/workspace/public/js/workspace.js"""))
    .pause(17 milliseconds)
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one.js")
    .get("""/infra/public/js/one.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .pause(98 milliseconds)
    .exec(http("get workspace i18n")
    .get("""/workspace/i18n""")
    .headers(headers_20))
    .pause(50 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("moment+langs.js")
    .get("""/infra/public/js/moment+langs.js""")
    .headers(headers_146)
    .check(status.in(Seq(200, 304))))
    .pause(32 milliseconds)
    .exec(http("underscore-min-1.4.4.js")
    .get("""/infra/public/js/underscore-min-1.4.4.js""")
    .headers(headers_146)
    .check(status.in(Seq(200, 304))))
    .pause(34 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo?_=1384423227867""")
    .headers(headers_20))
    .pause(16 milliseconds)
    .exec(http("get folders")
    .get("""/workspace/folders?filter=owner&_=1384423227864""")
    .headers(headers_20))
    .exec(http("get folders")
    .get("""/workspace/folders?filter=owner&_=1384423227865""")
    .headers(headers_20))
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .pause(32 milliseconds)
    .exec(http("get folders")
    .get("""/workspace/folders?filter=owner&_=1384423227869""")
    .headers(headers_20))
    .exec(http("get root documents")
    .get("""/workspace/documents?hierarchical=true&filter=owner&_=1384423227871""")
    .headers(headers_20))
    .pause(19 milliseconds)
    .exec(http("get shared folders")
    .get("""/workspace/folders?filter=shared&_=1384423227866""")
    .headers(headers_20))
    .pause(15 milliseconds)
    .exec(http("get folders")
    .get("""/workspace/folders?filter=owner&_=1384423227868""")
    .headers(headers_20))
    .exec(http("get shared folders")
    .get("""/workspace/folders?filter=shared&_=1384423227870""")
    .headers(headers_20))
    .pause(61 milliseconds)
    .exec(http("get shared documents")
    .get("""/workspace/documents?hierarchical=true&filter=shared&_=1384423227871""")
    .headers(headers_20)
    .check(status.is(200), jsonPath("$[0]._id").find.transform(_.orElse(Some(""))).saveAs("sharedDoc0Id")))
    .pause(19 milliseconds)
    .exec(http("get root documents")
    .get("""/workspace/documents?hierarchical=true&filter=owner&_=1384423227873""")
    .headers(headers_20))
    .pause(43 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .pause(29 milliseconds)
    .exec(http("empty document avatar")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_46))
    .exec(http("get user theme")
    .get("""/theme?token=0.7430935838724188""")
    .headers(headers_26))
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384423227874""")
    .headers(headers_20))
    .pause(14 milliseconds)
    .exec(http("get list-view template")
    .get("""/workspace/public/template/list-view.html""")
    .headers(headers_37))
    .pause(209 milliseconds)
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .pause(34 milliseconds)
    .exec(http("get icon avatar")
    .get("""/userbook/document/${meAvatar}?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_133)
    .check(status.in(Seq(200, 304))))
    .pause(112 milliseconds)
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(11 milliseconds)
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("add.png")
    .get("""/assets/themes/panda/img/icons/add.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("/user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(11 milliseconds)
    .exec(http("storage.png")
    .get("""/assets/themes/panda/img/icons/storage.png""")
    .headers(headers_38))
    .exec(http("show-icons.png")
    .get("""/assets/themes/panda/img/icons/show-icons.png""")
    .headers(headers_35))
    .doIf(session => session("sharedDoc0Id").asOption[String].getOrElse("") != "") {
    exec(http("get shared document ${sharedDoc0Id}")
      .get("""/workspace/document/${sharedDoc0Id}"""))
  }

  val chain_5 = exec(http("show-list-selected.png")
    .get("""/assets/themes/panda/img/icons/show-list-selected.png""")
    .headers(headers_38))
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .pause(21 milliseconds)
    .exec(http("folder.png")
    .get("""/assets/themes/panda/img/icons/folder.png""")
    .headers(headers_46))
    .pause(11 milliseconds)
    .exec(http("img.png")
    .get("""/assets/themes/panda/img/icons/img.png""")
    .headers(headers_46))
    .pause(235 milliseconds)
    .exec(http("list visibles users for rack send")
    .get("""/workspace/users/available-rack?_=1384423227872""")
    .headers(headers_20)
    .check(status.is(401)))
    .pause(4)
    .exec(http("close-2x.png")
    .get("""/assets/themes/panda/img/icons/close-2x.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("get create-file template")
    .get("""/workspace/public/template/create-file.html""")
    .headers(headers_37))
    .pause(9)
    .exec(http("loading.gif")
    .get("""/assets/themes/panda/img/illustrations/loading.gif""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(75 milliseconds)
    .exec(http("upload document")
    .post("""/workspace/document?thumbnail=120x120&name=6291049729_a5b5a3bdcc_o""")
    .headers(headers_337)
    .body(RawFileBody("TeacherSimulation_request_337.txt"))
    .check(status.is(201), jsonPath("$._id").find.saveAs("document0Id")))
    .pause(232 milliseconds)
    .exec(http("list root documents")
    .get("""/workspace/documents?hierarchical=true&filter=owner&_=1384423227875""")
    .headers(headers_20))
    .pause(5)
  val chain_6 = exec(http("get annuaire page")
    .get("""/userbook/annuaire?myClass=""")
    .headers(headers_1))
    .pause(29 milliseconds)
    .exec(http("moment+langs.js")
    .get("""/infra/public/js/moment+langs.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .check(status.in(Seq(200, 304))))
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("underscore-min-1.4.4.js")
    .get("""/infra/public/js/underscore-min-1.4.4.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular-sanitize-1.0.1.js")
    .get("""/infra/public/js/angular-sanitize-1.0.1.js"""))
    .exec(http("mustache.js")
    .get("""/infra/public/js/mustache.js"""))
    .pause(11 milliseconds)
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one.js")
    .get("""/infra/public/js/one.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("userbook.js")
    .get("""/directory/public/js/userbook.js"""))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .pause(126 milliseconds)
    .exec(http("get directory i18n")
    .get("""/directory/i18n"""))
    .pause(20 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo"""))
    .pause(43 milliseconds)
    .exec(http("get portal portal")
    .get("""/public/template/portal.html""")
    .check(status.in(Seq(200, 304))))
    .exec(http("get directory i18n")
    .get("""/directory/i18n"""))
    .pause(51 milliseconds)
    .exec(http("get user theme")
    .get("""/theme?token=0.25722223549487777"""))
    .pause(13 milliseconds)
    .exec(http("theme.css")
    .get("""/assets/themes/panda/default/theme.css""")
    .check(status.in(Seq(200, 304))))
    .exec(http("empty document avatar")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48"""))
    .pause(11 milliseconds)
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384539755983""")
    .headers(headers_20))
    .pause(55 milliseconds)
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_353)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_353)
    .check(status.in(Seq(200, 304))))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_353)
    .check(status.in(Seq(200, 304))))
    .exec(http("userbook.png")
    .get("""/assets/themes/panda/img/icons/userbook.png""")
    .headers(headers_353))
    .exec(http("show-details.png")
    .get("""/assets/themes/panda/img/icons/show-details.png""")
    .headers(headers_353))
    .exec(http("search.png")
    .get("""/assets/themes/panda/img/icons/search.png""")
    .headers(headers_353))
    .pause(12 milliseconds)
    .exec(http("show-icons-selected.png")
    .get("""/assets/themes/panda/img/icons/show-icons-selected.png""")
    .headers(headers_353))
    .pause(22 milliseconds)
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_354)
    .check(status.in(Seq(200, 304))))
    .pause(18 milliseconds)
    .exec(http("get default avatar")
    .get("""/userbook/document/no-avatar.jpg?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48"""))
    .pause(92 milliseconds)
    .exec(http("get class json")
    .get("""/userbook/api/class?_=1384539755984""")
    .headers(headers_20)
    .check(status.is(200), jsonPath("status").is("ok"),
    jsonPath("$.result").find.transform(_.map{res =>
      val json = JSONValue.parse(res).asInstanceOf[JSONObject]
      json.values.asScala.foldLeft[List[String]](Nil){(acc, c) =>
        val photo = c.asInstanceOf[JSONObject].get("photo").asInstanceOf[String]
        if (!photo.trim.isEmpty) {
          photo :: acc
        } else {
          acc
        }
      }
    }).saveAs("classAvatars"),
    jsonPath("$.result").find.transform(_.map{res =>
      val json = JSONValue.parse(res).asInstanceOf[JSONObject]
      json.values.asScala.foldLeft[List[List[String]]](Nil){(acc, c) =>
        val id = c.asInstanceOf[JSONObject].get("id").asInstanceOf[String]
        val userType = c.asInstanceOf[JSONObject].get("type").asInstanceOf[String]
        if (!id.trim.isEmpty && !userType.trim.isEmpty) {
          List(id, userType) :: acc
        } else {
          acc
        }
      }
    }).saveAs("classUsers")))
    .pause(113 milliseconds)
    .exec(http("happy-panda.png")
    .get("""/assets/themes/panda/img/icons/happy-panda.png""")
    .headers(headers_353))
    .exec(http("view-book.png")
    .get("""/assets/themes/panda/img/icons/view-book.png""")
    .headers(headers_353))
    .exec(http("send-mail.png")
    .get("""/assets/themes/panda/img/icons/send-mail.png""")
    .headers(headers_353))
    .exec(http("view-folder.png")
    .get("""/assets/themes/panda/img/icons/view-folder.png""")
    .headers(headers_353))
    .pause(13 milliseconds)
    .exec(http("default-panda-60px.png")
    .get("""/assets/themes/panda/img/icons/default-panda-60px.png""")
    .headers(headers_353))
    .pause(19 milliseconds)
    .foreach("${classAvatars}", "uAvatar") {
    exec(http("get user avatar")
      .get("""/userbook/document/${uAvatar}?userbook-dimg=public/img/no-avatar.jpg&thumbnail=82x82""")
      .headers(headers_46))
      .pause(78 milliseconds)
  }
    .exec(http("show-icons.png")
    .get("""/assets/themes/panda/img/icons/show-icons.png"""))
    .exec(http("show-details-selected.png")
    .get("""/assets/themes/panda/img/icons/show-details-selected.png"""))
    .exec(http("view-book-white.png")
    .get("""/assets/themes/panda/img/icons/view-book-white.png"""))
    .exec(http("view-folder-white.png")
    .get("""/assets/themes/panda/img/icons/view-folder-white.png"""))
    .pause(5)
    .foreach("${classUsers}", "classUser") {
    exec(http("get class user infos")
      .get("""/userbook/api/person?id=${classUser(0)}&type=${classUser(1)}&_=1384539755988""")
      .headers(headers_46))
      .pause(5)
  }
    .exec(http("Search users")
    .get("""/userbook/api/search?name=&_=1384539755985"""))
    .pause(69 milliseconds)
    .exec(http("Search users")
    .get("""/userbook/api/search?name=mel&_=1384539755986"""))
    .pause(3)
    .exec(http("Search users")
    .get("""/userbook/api/search?name=fre&_=1384539755987"""))
    .pause(5)
    .exec(http("logout")
    .get("""/auth/logout?callback=""")
    .headers(headers_1)
    .check(status.is(302)))
    .exec(http("get root page")
    .get("""/""")
    .headers(headers_1)
    .check(status.is(302)))
    .exec(http("get login page")
    .get("""/auth/login?callback=http://one/""")
    .headers(headers_1))
    .pause(24 milliseconds)
    .exec(http("auth.css")
    .get("""/auth/public/css/auth.css""")
    .headers(headers_351)
    .check(status.in(Seq(200, 304))))
    .exec(http("auth.js")
    .get("""/auth/public/js/auth.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("auth.png")
    .get("""/auth/public/img/auth.png""")
    .headers(headers_353)
    .check(status.in(Seq(200, 304))))
    .pause(33 milliseconds)
    .exec(http("KGJuneBug.ttf")
    .get("""/auth/public/fonts/KGJuneBug.ttf""")
    .headers(headers_354)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/current/assets/img/illustrations/logo.png""")
    .headers(headers_353)
    .check(status.in(Seq(200, 304))))

  val scn = scenario("Student Scenario").exec(
    chain_0, chain_1, chain_2, chain_3, chain_4, chain_5, chain_6)

}
