package org.entcore.test.load

import io.gatling.http.Predef._
import io.gatling.core.Predef._
import bootstrap._
import java.net.URLEncoder
import scala.concurrent.duration._

object TeacherScenario {

  val headers_1 = Map("""Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_4 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_5 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_7 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_8 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""",
    """Content-Type""" -> """application/x-www-form-urlencoded""")

  val headers_20 = Map("""X-Requested-With""" -> """XMLHttpRequest""")

  val headers_22 = Map(
    """Accept""" -> """application/json, text/plain, */*""")

  val headers_23 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_24 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_26 = Map(
    """Accept""" -> """application/json, text/javascript, */*; q=0.01""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_30 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_35 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_37 = Map("""Accept""" -> """application/json, text/plain, */*""")

  val headers_38 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_45 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_46 = Map("""Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_99 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_109 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_119 = Map(
    """Accept""" -> """application/json, text/plain, */*""")

  val headers_120 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_123 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_125 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_131 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_133 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_146 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val headers_159 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_160 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_178 = Map("""Accept""" -> """text/css,*/*;q=0.1""")

  val headers_186 = Map(
    """Cache-Control""" -> """no-cache""",
    """Content-Type""" -> """multipart/form-data; boundary=---------------------------10797810774189015011942205288""",
    """Pragma""" -> """no-cache""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_188 = Map(
    """Cache-Control""" -> """no-cache""",
    """Content-Type""" -> """application/x-www-form-urlencoded; charset=UTF-8""",
    """Pragma""" -> """no-cache""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_207 = Map(
    """Cache-Control""" -> """no-cache""",
    """Content-Type""" -> """multipart/form-data; boundary=---------------------------1289423945374670221677674784""",
    """Pragma""" -> """no-cache""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_337 = Map(
    """Cache-Control""" -> """no-cache""",
    """Content-Type""" -> """multipart/form-data; boundary=---------------------------157465906117855667891860310867""",
    """Pragma""" -> """no-cache""",
    """X-Requested-With""" -> """XMLHttpRequest""")

  val headers_342 = Map(
    """Accept""" -> """application/json, text/plain, */*""")

  val headers_351 = Map(
    """Accept""" -> """text/css,*/*;q=0.1""")

  val headers_353 = Map(
    """Accept""" -> """image/png,image/*;q=0.8,*/*;q=0.5""")

  val headers_354 = Map(
    """Accept""" -> """text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8""")

  val chain_0 = exec(http("get root page")
    .get("""/""")
    .headers(headers_1)
    .check(status.is(302)))
    .pause(90 milliseconds)
    .exec(http("get  login page")
    .get("""/auth/login?callback=http://one/""")
    .headers(headers_1))
    .pause(71 milliseconds)
    .exec(http("auth.js")
    .get("""/auth/public/js/auth.js"""))
    .exec(http("auth.css")
    .get("""/auth/public/css/auth.css""")
    .headers(headers_4))
    .exec(http("auth.png")
    .get("""/auth/public/img/auth.png""")
    .headers(headers_5))
    .pause(33 milliseconds)
    .exec(http("logo.png")
    .get("""/auth/public/img/illustrations/logo.png""")
    .headers(headers_5))
    .pause(40 milliseconds)
    .exec(http("KGJuneBug.ttf")
    .get("""/auth/public/fonts/KGJuneBug.ttf""")
    .headers(headers_7))
    .pause(7)
    .feed(ssv("teachers.csv"))
    .exec(http("log user")
    .post("""/auth/login""")
    .headers(headers_8)
    .param("""email""", """${login}""")
    .param("""password""", """${code}${code}""")
    .check(status.is(302)))
    .pause(76 milliseconds)
    .exec(http("get root page (authenticated)")
    .get("""/""")
    .headers(headers_1))
    .pause(67 milliseconds)
    .exec(http("get timeline page")
    .get("""/timeline/timeline""")
    .headers(headers_1))
    .pause(21 milliseconds)
    .exec(http("timeline.js")
    .get("""/timeline/public/js/timeline.js"""))
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js"""))
    .pause(61 milliseconds)
    .exec(http("one.js")
    .get("""/infra/public/js/one.js"""))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js"""))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js"""))
    .pause(13 milliseconds)
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js"""))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js"""))
    .pause(11 milliseconds)
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js"""))
    .pause(48 milliseconds)
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js"""))
    .pause(136 milliseconds)
    .exec(http("get timeline i18n")
    .get("""/timeline/i18n""")
    .headers(headers_20))
    .pause(68 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("get portal page")
    .get("""/public/template/portal.html""")
    .headers(headers_22))
    .pause(42 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_23))
    .exec(http("underscore-min-1.4.4.js")
    .get("""/infra/public/js/underscore-min-1.4.4.js""")
    .headers(headers_24))
    .pause(36 milliseconds)
    .exec(http("get widgets json")
    .get("""/timeline/public/json/widgets.json?_=1384422780883""")
    .headers(headers_20))
    .exec(http("get user theme")
    .get("""/theme?token=0.46356402737929747""")
    .headers(headers_26))
    .pause(20 milliseconds)
    .exec(http("moment+langs.js")
    .get("""/infra/public/js/moment+langs.js""")
    .headers(headers_24))
    .exec(http("calendar.js")
    .get("""/timeline/public/js/calendar.js"""))
    .pause(30 milliseconds)
    .exec(http("birthday.js")
    .get("""/directory/public/js/birthday.js"""))
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_30))
    .pause(44 milliseconds)
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384422780882""")
    .headers(headers_20))
    .pause(78 milliseconds)
    .exec(http("get availables themes json")
    .get("""/timeline/public/json/themes.json?_=1384422780888""")
    .headers(headers_20))
    .pause(11 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo?_=1384422780886""")
    .headers(headers_20))
    .pause(15 milliseconds)
    .exec(http("get timeline types")
    .get("""/timeline/types?_=1384422780885""")
    .headers(headers_20))
    .pause(35 milliseconds)
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_35))
    .pause(65 milliseconds)
    .exec(http("get birthdays")
    .get("""/userbook/person/birthday?_=1384422780884""")
    .headers(headers_20)
    .check(status.is(200),
    jsonPath("$..id").findAll.saveAs("birthdayUsers")))
    .exec(http("get birthday page")
    .get("""/userbook/birthday""")
    .headers(headers_37))
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_38))
    .pause(337 milliseconds)
    .exec(http("get calendar page")
    .get("""/timeline/calendar""")
    .headers(headers_37))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_35))
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_35))
    .exec(http("tools.png")
    .get("""/assets/themes/panda/img/icons/tools.png""")
    .headers(headers_35))
    .exec(http("notification.png")
    .get("""/assets/themes/panda/img/icons/notification.png""")
    .headers(headers_35))
    .exec(http("get timeline events")
    .get("""/timeline/lastNotifications?_=1384422780887""")
    .headers(headers_20)
    .check(status.is(200), jsonPath("status").is("ok"),
    jsonPath("$.results..sender").findAll.transform(_.orElse(Some(Nil))).saveAs("senders")))
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_45))
    .pause(67 milliseconds)
    .foreach("${birthdayUsers}", "bUserId") {
    exec(http("get birthday avatar")
      .get("""/userbook/avatar/${bUserId}?thumbnail=48x48""")
      .check(status.in(Seq(200, 301)), header("Location").find.transform(_.orElse(Some(""))).saveAs("avatarUser")))
      .pause(12 milliseconds)
      .doIf(session => session("avatarUser").asOption[String].getOrElse("") != "") {
      exec(http("get birthday avatar (after redirect)")
        .get("""${avatarUser}""")
        .headers(headers_46)
      )
    }
  }
    .pause(13 milliseconds)
    .exec(http("default/thumbnail.png")
    .get("""/assets/themes/panda/default/thumbnail.png""")
    .headers(headers_35))
    .exec(http("hills/thumbnail.png")
    .get("""/assets/themes/panda/hills/thumbnail.png""")
    .headers(headers_35))
    .pause(21 milliseconds)
    .exec(http("desert/thumbnail.png")
    .get("""/assets/themes/panda/desert/thumbnail.png""")
    .headers(headers_35))
    .exec(http("panda-food/thumbnail.png")
    .get("""/assets/themes/panda/panda-food/thumbnail.png""")
    .headers(headers_35))
    .pause(66 milliseconds)
    .exec(http("sparkly/thumbnail.png")
    .get("""/assets/themes/panda/sparkly/thumbnail.png""")
    .headers(headers_35))
    .pause(11 milliseconds)

  val chain_1 = exec(http("birthdays-header-fr.png")
    .get("""/assets/themes/panda/img/illustrations/birthdays-header-fr.png""")
    .headers(headers_35))
    .exec(http("share.png")
    .get("""/assets/themes/panda/img/icons/share.png""")
    .headers(headers_35))
    .exec(http("blog.png")
    .get("""/assets/themes/panda/img/icons/blog.png""")
    .headers(headers_35))
    .pause(118 milliseconds)
    .foreach("${senders}", "senderId") {
    exec(http("get timeline event avatar")
      .get("""/userbook/avatar/${senderId}?thumbnail=82x82""")
      .check(status.in(Seq(200, 301)), header("Location").find.transform(_.orElse(Some(""))).saveAs("avatarUser")))
      .pause(12 milliseconds)
      .doIf(session => session("avatarUser").asOption[String].getOrElse("") != "") {
      exec(http("get timeline event avatar (after redirect)")
        .get("""${avatarUser}""")
        .headers(headers_7)
      )
    }
  }
    .exec(http("calendar-header.png")
    .get("""/assets/themes/panda/img/illustrations/calendar-header.png""")
    .headers(headers_35))
    .exec(http("calendar-separator.png")
    .get("""/assets/themes/panda/img/illustrations/calendar-separator.png""")
    .headers(headers_35))
    .pause(27 milliseconds)
    .exec(http("get applications page")
    .get("""/apps""")
    .headers(headers_1))
    .pause(17 milliseconds)
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("app.css")
    .get("""/public/css/app.css""")
    .headers(headers_109))
    .pause(14 milliseconds)
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .pause(12 milliseconds)
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .pause(98 milliseconds)
    .exec(http("get applications i18n")
    .get("""/apps/i18n""")
    .headers(headers_20)
    .check(status.is(404)))
    .pause(46 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .pause(31 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .pause(21 milliseconds)
    .exec(http("get user theme")
    .get("""/theme?token=0.03805585759766428""")
    .headers(headers_26))
    .pause(15 milliseconds)
    .exec(http("empty document avatar")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_46))
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384422792736""")
    .headers(headers_20)
    .check(status.is(200), jsonPath("status").is("ok"),
    jsonPath("$.result.0.photo").find.saveAs("meAvatar")))
    .pause(36 milliseconds)
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("blog-large.png")
    .get("""/assets/themes/panda/img/icons/blog-large.png""")
    .headers(headers_35))
    .pause(12 milliseconds)
    .exec(http("workspace-large.png")
    .get("""/assets/themes/panda/img/icons/workspace-large.png""")
    .headers(headers_35))
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .exec(http("apps.png")
    .get("""/assets/themes/panda/img/icons/apps.png""")
    .headers(headers_35))
    .pause(18 milliseconds)
    .exec(http("get icon avatar")
    .get("""/userbook/document/${meAvatar}?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_133)
    .check(status.in(Seq(200, 304))))
    .pause(3)
    .exec(http("get blog page")
    .get("""/blog""")
    .headers(headers_1))

  val chain_2 = pause(28 milliseconds)
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("blog.js")
    .get("""/blog/public/js/blog.js"""))
    .pause(22 milliseconds)
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one.js")
    .get("""/infra/public/js/one.js""")
    .check(status.in(Seq(200, 304))))
    .pause(97 milliseconds)
    .exec(http("get blog i18n")
    .get("""/blog/i18n""")
    .headers(headers_20))
    .pause(83 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("moment+langs.js")
    .get("""/infra/public/js/moment+langs.js""")
    .headers(headers_146)
    .check(status.in(Seq(200, 304))))
    .pause(30 milliseconds)
    .exec(http("underscore-min-1.4.4.js")
    .get("""/infra/public/js/underscore-min-1.4.4.js""")
    .headers(headers_146)
    .check(status.in(Seq(200, 304))))
    .pause(23 milliseconds)
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo?_=1384422796869""")
    .headers(headers_20))
    .pause(52 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .pause(19 milliseconds)
    .exec(http("empty document avatar")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_46))
    .pause(26 milliseconds)
    .exec(http("list all blogs")
    .get("""/blog/list/all?_=1384422796870""")
    .headers(headers_20)
    .check(status.is(200),
    jsonPath("$.._id").findAll.transform(_.orElse(Some(Nil))).saveAs("blogsIds"),
    jsonPath("$..thumbnail").findAll.transform(_.orElse(Some(Nil))).saveAs("blogsThumbnails")))
    .exec(http("get user theme")
    .get("""/theme?token=0.2530770265949154""")
    .headers(headers_26))
    .pause(13 milliseconds)
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384422796872""")
    .headers(headers_20))
    .exec(http("list all blogs")
    .get("""/blog/list/all?_=1384422796871""")
    .headers(headers_20))
    .pause(71 milliseconds)
    .foreach("${blogsIds}", "blogId") { // User read each blog
    exec(http("list posts in blog ${blogId}")
      .get("""/blog/post/list/all/${blogId}?_=1384422796873""")
      .check(status.is(200),
      jsonPath("$.._id").findAll.transform(_.orElse(Some(Nil))).saveAs("postsIds")))  // TODO parse content in first post to find images
      .pause(42 milliseconds)
      .doIf(session => session("postsIds").asOption[List[String]].getOrElse(Nil) != Nil) {
      foreach("${postsIds}", "postId") {
        exec(http("get comments in post ${postId}")
          .get("""/blog/comments/${blogId}/${postId}?_=1384422796875""")
          .headers(headers_20))
      }
    }
      .pause(300) // 5 min to read one blog
  }
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .pause(43 milliseconds)
    .foreach("${blogsThumbnails}", "blogThumb") {
    exec(http("get blog thumbnail")
      .get("""$blogThumb""")
      .headers(headers_46))
      .pause(78 milliseconds)
  }
    .exec(http("get icon avatar")
    .get("""/userbook/document/${meAvatar}?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_133)
    .check(status.in(Seq(200, 304))))
    .exec(http("add.png")
    .get("""/assets/themes/panda/img/icons/add.png""")
    .headers(headers_38))
    .pause(15 milliseconds)
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(95 milliseconds)
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("blog.png")
    .get("""/assets/themes/panda/img/icons/blog.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(58 milliseconds)
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(3)
    .exec(http("get create post template")
    .get("""/blog/public/template/create-post.html""")
    .headers(headers_37))
    .pause(46 milliseconds)
    .exec(http("ckeditor.js")
    .get("""/infra/public/ckeditor/ckeditor.js""")
    .headers(headers_1))
    .pause(153 milliseconds)
    .exec(http("config.js")
    .get("""/infra/public/ckeditor/config.js?t=D8AD"""))
    .pause(13 milliseconds)
    .exec(http("editor_gecko.css")
    .get("""/infra/public/ckeditor/skins/moono/editor_gecko.css?t=D8AD""")
    .headers(headers_178))
    .exec(http("fr.js")
    .get("""/infra/public/ckeditor/lang/fr.js?t=D8AD"""))
    .pause(25 milliseconds)
    .exec(http("styles.js")
    .get("""/infra/public/ckeditor/styles.js?t=D8AD"""))
    .exec(http("plugin.js")
    .get("""/infra/public/ckeditor/plugins/upload/plugin.js?t=D8AD"""))
    .pause(67 milliseconds)
    .exec(http("icons.png")
    .get("""/infra/public/ckeditor/skins/moono/icons.png""")
    .headers(headers_46))
    .exec(http("upload.png")
    .get("""/infra/public/ckeditor/plugins/upload/icons/upload.png?t=D8AD""")
    .headers(headers_46))
    .pause(7)
    .exec(http("get create blog template")
    .get("""/blog/public/template/create-blog.html""")
    .headers(headers_37))
    .pause(51 milliseconds)
    .exec(http("blog.png")
    .get("""/blog/public/img/blog.png""")
    .headers(headers_46))
    .pause(106)
    .exec(http("upload blog image")
    .post("""/workspace/document?application=blog-newblog&protected=true&thumbnail=100x100&name=classe-2.jpg""")
    .headers(headers_186)
    .body(RawFileBody("TeacherSimulation_request_186.txt"))
    .check(status.is(201), jsonPath("$._id").find.saveAs("newBlogThumb")))
    .pause(61 milliseconds)
    .exec(http("get new blog thumbnail")
    .get("""/workspace/document/${newBlogThumb}?thumbnail=100x100""")
    .headers(headers_46))
    .pause(11)
    .exec(http("create new blog")
    .post("""/blog""")
    .headers(headers_188)
    .param("""thumbnail""", """/workspace/document/${newBlogThumb}?thumbnail=100x100""")
    .param("""comment-type""", """IMMEDIATE""")
    .param("""publish-type""", """IMMEDIATE""")
    .param("""description""", """""")
    .param("""title""", """Le blog de la classe""")
    .check(status.is(200), jsonPath("$._id").find.saveAs("newBlogId")))
    .pause(36 milliseconds)
    .exec(http("list all blogs")
    .get("""/blog/list/all?_=1384422796870""")
    .headers(headers_20)
    .check(status.is(200)))
    .exec(http("list post in new blog")
    .get("""/blog/post/list/all/${newBlogId}?_=1384422796878""")
    .headers(headers_20))
    .exec(http("list post in new blog")
    .get("""/blog/post/list/all/${newBlogId}?_=1384422796879""")
    .headers(headers_20))
    .pause(23)
    .exec(http("get blog infos")
    .get("""/blog/${newBlogId}?_=1384422796880""")
    .headers(headers_20))
    .pause(12 milliseconds)
    .exec(http("get edit blog template")
    .get("""/blog/public/template/edit-blog.html""")
    .headers(headers_37))
    .pause(1)
    .exec(http("close-2x.png")
    .get("""/assets/themes/panda/img/icons/close-2x.png""")
    .headers(headers_38))
    .exec(http("get share template")
    .get("""/blog/public/template/share.html""")
    .headers(headers_37))
    .pause(17 milliseconds)
    .exec(http("get share-panel template")
    .get("""/infra/public/template/share-panel.html""")
    .headers(headers_37))
    .pause(543 milliseconds)
    .exec(http("get share blog ${newBlogId} json")
    .get("""/blog/share/json/${newBlogId}?_=1384422796881""")
    .headers(headers_20)
    .check(status.is(200), // TODO save actions to use it dynamically to share
    jsonPath("$.groups.visibles[0].id").find.saveAs("profilGroupParentsSchoolId"),
    jsonPath("$.groups.visibles[1].id").find.saveAs("profilGroupTeachersSchoolId"),
    jsonPath("$.groups.visibles[2].id").find.saveAs("profilGroupStudentsSchoolId")
  ))

  val chain_3 = pause(44)
    .exec(http("close.png")
    .get("""/assets/themes/panda/img/icons/close.png""")
    .headers(headers_46))
    .pause(1)
    .exec(http("checkbox-checked.png")
    .get("""/assets/themes/panda/img/icons/checkbox-checked.png""")
    .headers(headers_46))
    .pause(113 milliseconds)
    .exec(http("share blog ${newBlogId} to parents (read)")
    .put("""/blog/share/json/${newBlogId}""")
    .bodyPart(StringBodyPart("""groupId""", """${profilGroupParentsSchoolId}"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|comments"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|get"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-BlogController|get"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|list""")))
    .pause(3)
    .exec(http("share blog ${newBlogId} to teachers (read)")
    .put("""/blog/share/json/${newBlogId}""")
    .bodyPart(StringBodyPart("""groupId""", """${profilGroupTeachersSchoolId}"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|comments"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|get"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-BlogController|get"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|list""")))
    .pause(1)
    .exec(http("share blog ${newBlogId} to teachers (contrib)")
    .put("""/blog/share/json/${newBlogId}""")
    .bodyPart(StringBodyPart("""groupId""", """${profilGroupTeachersSchoolId}"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|unpublish"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|create"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|delete"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|update"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|submit""")))
    .pause(1)
    .exec(http("share blog ${newBlogId} to teachers (comment)")
    .put("""/blog/share/json/${newBlogId}""")
    .bodyPart(StringBodyPart("""groupId""", """${profilGroupTeachersSchoolId}"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|deleteComment"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|comment""")))
    .pause(1)
    .exec(http("share blog ${newBlogId} to students (read)")
    .put("""/blog/share/json/${newBlogId}""")
    .bodyPart(StringBodyPart("""groupId""", """${profilGroupStudentsSchoolId}"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|comments"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|get"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-BlogController|get"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|list""")))
    .pause(1)
    .exec(http("share blog ${newBlogId} to students (comment)")
    .put("""/blog/share/json/${newBlogId}""")
    .bodyPart(StringBodyPart("""groupId""", """${profilGroupStudentsSchoolId}"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|deleteComment"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-blog-controllers-PostController|comment""")))
    .pause(25)
    .exec(http("list posts in blog ${newBlogId}")
    .get("""/blog/post/list/all/${newBlogId}?_=1384422796882""")
    .headers(headers_20))
    .pause(312 milliseconds)
    .exec(http("get share blog ${newBlogId} json")
    .get("""/blog/share/json/${newBlogId}?_=1384422796883""")
    .headers(headers_20))
    .pause(94)
    .exec(http("loading.gif")
    .get("""/assets/themes/panda/img/illustrations/loading.gif""")
    .headers(headers_35))
    .pause(20 milliseconds)
    .exec(http("upload image in post")
    .post("""/workspace/document?application=blog-&protected=true&name=7406107662_49df982c16_o.jpg""")
    .headers(headers_207)
    .body(RawFileBody("TeacherSimulation_request_207.txt"))
    .check(status.is(201), jsonPath("$._id").find.saveAs("imgPost0")))
    .pause(54 milliseconds)
    .exec(http("get uploaded image in post")
    .get("""/workspace/document/${imgPost0}""")
    .headers(headers_46))
    .pause(10)
    .exec(http("create post in blog ${newBlogId}")
    .post("""/blog/post/${newBlogId}""")
    .headers(headers_188)
    .param("""state""", """DRAFT""")
    .param("""title""", """Le premier billet de la classe""")
    .param("""content""", """<p style="text-align: justify; font-size: 10.909090995788574px; line-height: 14px; margin: 0px 0px 14px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ac quam in leo sodales commodo. Fusce vulputate hendrerit erat non elementum. Mauris aliquam pellentesque quam ut ullamcorper. Maecenas ornare justo eget justo aliquet, quis placerat nisi blandit. Fusce ac sagittis sem, eget auctor turpis. Curabitur libero nunc, mattis quis laoreet in, sagittis ut nibh. Nunc vestibulum sapien nisl. Donec sodales volutpat neque, nec dignissim risus dapibus ac. Praesent eros sapien, dictum eget urna non, accumsan vehicula dui. Vivamus neque nibh, iaculis nec mattis ut, condimentum vitae ligula. Nulla metus erat, tempus id tellus in, porttitor auctor odio. Vivamus dictum aliquet urna id placerat. Praesent a leo sed velit blandit ornare sed nec nulla. Nullam sed risus vitae tortor molestie iaculis nec nec nunc. Nullam interdum nec felis in suscipit.<br></p><p style="text-align: justify; font-size: 10.909090995788574px; line-height: 14px; margin: 0px 0px 14px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">In tristique cursus sapien, id sollicitudin purus cursus vitae. Nunc dolor libero, rutrum et commodo quis, congue sit amet lorem. Nullam bibendum commodo nunc, eu gravida dolor venenatis id. Etiam consectetur, leo ac vestibulum faucibus, ligula dolor vulputate erat, ut ornare dui tellus ut felis. Praesent vitae faucibus quam, vel aliquam sapien. Aenean semper, arcu a aliquet mollis, augue magna eleifend mauris, sit amet egestas nunc eros vitae ligula. Vestibulum bibendum orci nisi, in consectetur lacus sagittis ac.</p><p style="text-align: justify; font-size: 10.909090995788574px; line-height: 14px; margin: 0px 0px 14px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Sed et turpis accumsan, lobortis lacus eu, lobortis mauris. Maecenas id odio ornare, pretium elit sit amet, lobortis justo. Pellentesque sit amet gravida lacus. Maecenas et eros ut sem elementum lacinia vitae id dolor. Curabitur elementum imperdiet est, ut adipiscing erat pretium a. Integer ut ligula sit amet elit tincidunt hendrerit a in ante. Phasellus rutrum lectus et est sagittis, vitae lacinia ante ultricies. Aliquam malesuada orci nisi, sit amet lacinia ligula auctor et. Fusce eu luctus leo. Integer ac arcu at quam adipiscing ullamcorper. Maecenas ipsum ante, mollis id erat id, blandit posuere urna. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id bibendum turpis.</p><p style="text-align: justify; font-size: 10.909090995788574px; line-height: 14px; margin: 0px 0px 14px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><img src="/workspace/document/${imgPost0}"><br></p><p style="text-align: justify; font-size: 10.909090995788574px; line-height: 14px; margin: 0px 0px 14px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Duis hendrerit malesuada libero, id lobortis felis sollicitudin vestibulum. In hac habitasse platea dictumst. Mauris id libero sed dui condimentum placerat ut quis lectus. Morbi imperdiet laoreet rhoncus. Quisque fermentum, orci sit amet lobortis posuere, est ligula accumsan sem, quis semper erat dolor ut ante. Ut egestas felis id tortor semper, vitae convallis sem vulputate. Ut auctor dui nec tortor pretium suscipit. Morbi tincidunt nunc sit amet erat pretium fermentum. Integer ac velit at metus iaculis tempus non id neque. Nam sodales pretium vulputate. Aliquam mi arcu, tristique at lorem vel, consequat posuere odio.<br></p><p style="text-align: justify; font-size: 10.909090995788574px; line-height: 14px; margin: 0px 0px 14px; padding: 0px; color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Nam scelerisque, felis nec auctor ultricies, nibh nisl tempus ipsum, ut pellentesque neque eros sed nisi. Cras metus erat, tempus imperdiet pellentesque malesuada, aliquam a turpis. Fusce non mattis ipsum. Etiam vulputate luctus nisl eget pharetra. Ut in adipiscing tellus. Nulla quis est lacinia sem commodo luctus. Curabitur eros dui, consequat euismod sagittis vel, congue eget purus. Vivamus eu pretium mauris. Nam magna urna, condimentum sed euismod eu, ultricies a risus. Nulla risus urna, mollis sed faucibus sed, pretium ut nisi. Vivamus pellentesque auctor tortor, quis venenatis turpis rutrum sit amet. Integer quis lobortis nibh. Phasellus facilisis volutpat lacinia. Nullam adipiscing imperdiet viverra. Pellentesque nec massa tempus, cursus orci ut, tempor turpis.<br></p>""")
    .check(status.is(200), jsonPath("$._id").find.saveAs("post0Id")))
    .pause(77 milliseconds)
    .exec(http("submit post ${post0Id} (change state)")
    .put("""/blog/post/submit/${newBlogId}/${post0Id}""")
    .header("Content-Length", "0"))
    .pause(44 milliseconds)
    .exec(http("list posts in blog ${newBlogId}")
    .get("""/blog/post/list/all/${newBlogId}?_=1384422796884""")
    .headers(headers_20))
    .pause(53 milliseconds)
    .exec(http("get comments in post ${post0Id}")
    .get("""/blog/comments/${newBlogId}/${post0Id}?_=1384422796885""")
    .headers(headers_20))
    .pause(8)
    .exec(http("get comment-post template")
    .get("""/blog/public/template/comment-post.html""")
    .headers(headers_37))
    .pause(24)
    .feed(ssv("citations.csv").circular)
    .exec{session =>
    session.set("encodedCitation", URLEncoder.encode(
      session("citation").as[String] + " - " + session("author").as[String], "UTF-8"))
  }
    .exec(http("add comment in post ${post0Id}")
    .post("""/blog/comment/${newBlogId}/${post0Id}""")
    .headers(headers_188)
    .param("""comment""", """${encodedCitation}"""))
    .pause(29 milliseconds)
    .exec(http("get comments in post ${post0Id}")
    .get("""/blog/comments/${newBlogId}/${post0Id}?_=1384422796886""")
    .headers(headers_20))
    .pause(9)
    .exec(http("get applications page")
    .get("""/apps""")
    .headers(headers_1))
    .pause(15 milliseconds)
    .exec(http("app.css")
    .get("""/public/css/app.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .pause(20 milliseconds)
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one.js")
    .get("""/infra/public/js/one.js""")
    .check(status.in(Seq(200, 304))))
    .pause(109 milliseconds)
    .exec(http("get apps i18n")
    .get("""/apps/i18n""")
    .headers(headers_20)
    .check(status.is(404)))
    .pause(45 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .pause(48 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .pause(12 milliseconds)
    .exec(http("empty document avatar")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_46))
    .exec(http("get user theme")
    .get("""/theme?token=0.3242081556025924""")
    .headers(headers_26))
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384423216724""")
    .headers(headers_20))
    .pause(17 milliseconds)
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .pause(18 milliseconds)
    .exec(http("get icon avatar")
    .get("""/userbook/document/${meAvatar}?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_133)
    .check(status.in(Seq(200, 304))))
    .pause(24 milliseconds)
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("apps.png")
    .get("""/assets/themes/panda/img/icons/apps.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("workspace-large.png")
    .get("""/assets/themes/panda/img/icons/workspace-large.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("blog-large.png")
    .get("""/assets/themes/panda/img/icons/blog-large.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(1)
    .exec(http("get workspace page")
    .get("""/workspace/workspace""")
    .headers(headers_1))
    .pause(15 milliseconds)
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("workspace.js")
    .get("""/workspace/public/js/workspace.js"""))
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .pause(17 milliseconds)
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one.js")
    .get("""/infra/public/js/one.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .pause(134 milliseconds)
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .exec(http("get workspace i18n")
    .get("""/workspace/i18n""")
    .headers(headers_20))
    .pause(39 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("get user theme")
    .get("""/theme?token=0.6614103632515401""")
    .headers(headers_26))
    .pause(25 milliseconds)
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .pause(30 milliseconds)
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))

  val chain_4 = pause(11 milliseconds)
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .pause(6)
    .exec(http("get apps page")
    .get("""/apps""")
    .headers(headers_1))
    .pause(13 milliseconds)
    .exec(http("app.css")
    .get("""/public/css/app.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .pause(16 milliseconds)
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .pause(12 milliseconds)
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .pause(15 milliseconds)
    .exec(http("one.js")
    .get("""/infra/public/js/one.js""")
    .check(status.in(Seq(200, 304))))
    .pause(74 milliseconds)
    .exec(http("get apps i18n")
    .get("""/apps/i18n""")
    .headers(headers_20)
    .check(status.is(404)))
    .pause(50 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .pause(36 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .pause(13 milliseconds)
    .exec(http("empty document avatar")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_46))
    .exec(http("get user theme")
    .get("""/theme?token=0.2172852787006575""")
    .headers(headers_26))
    .pause(14 milliseconds)
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384423225498""")
    .headers(headers_20))
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .pause(32 milliseconds)
    .exec(http("get icon avatar")
    .get("""/userbook/document/${meAvatar}?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_133)
    .check(status.in(Seq(200, 304))))
    .pause(20 milliseconds)
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("workspace-large.png")
    .get("""/assets/themes/panda/img/icons/workspace-large.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(11 milliseconds)
    .exec(http("blog-large.png")
    .get("""/assets/themes/panda/img/icons/blog-large.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("apps.png")
    .get("""/assets/themes/panda/img/icons/apps.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .pause(2)
    .exec(http("get workspace page")
    .get("""/workspace/workspace""")
    .headers(headers_1))
    .pause(13 milliseconds)
    .exec(http("one-loader.js")
    .get("""/infra/public/js/one-loader.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("workspace.js")
    .get("""/workspace/public/js/workspace.js"""))
    .pause(17 milliseconds)
    .exec(http("jquery-1.9.1.js")
    .get("""/infra/public/js/jquery-1.9.1.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular.min.js")
    .get("""/infra/public/js/angular.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("angular-sanitize.min.js")
    .get("""/infra/public/js/angular-sanitize.min.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one-app.js")
    .get("""/infra/public/js/one-app.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("one.js")
    .get("""/infra/public/js/one.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("ui.js")
    .get("""/infra/public/js/ui.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("humane.min.js")
    .get("""/infra/public/js/humane.min.js""")
    .check(status.in(Seq(200, 304))))
    .pause(98 milliseconds)
    .exec(http("get workspace i18n")
    .get("""/workspace/i18n""")
    .headers(headers_20))
    .pause(50 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo""")
    .headers(headers_20))
    .exec(http("moment+langs.js")
    .get("""/infra/public/js/moment+langs.js""")
    .headers(headers_146)
    .check(status.in(Seq(200, 304))))
    .pause(32 milliseconds)
    .exec(http("underscore-min-1.4.4.js")
    .get("""/infra/public/js/underscore-min-1.4.4.js""")
    .headers(headers_146)
    .check(status.in(Seq(200, 304))))
    .pause(34 milliseconds)
    .exec(http("get user infos")
    .get("""/auth/oauth2/userinfo?_=1384423227867""")
    .headers(headers_20))
    .pause(16 milliseconds)
    .exec(http("get folders")
    .get("""/workspace/folders?filter=owner&_=1384423227864""")
    .headers(headers_20))
    .exec(http("get folders")
    .get("""/workspace/folders?filter=owner&_=1384423227865""")
    .headers(headers_20))
    .exec(http("get portal template")
    .get("""/public/template/portal.html""")
    .headers(headers_119)
    .check(status.in(Seq(200, 304))))
    .pause(32 milliseconds)
    .exec(http("get folders")
    .get("""/workspace/folders?filter=owner&_=1384423227869""")
    .headers(headers_20))
    .exec(http("get root documents")
    .get("""/workspace/documents?hierarchical=true&filter=owner&_=1384423227871""")
    .headers(headers_20))
    .pause(19 milliseconds)
    .exec(http("get shared folders")
    .get("""/workspace/folders?filter=shared&_=1384423227866""")
    .headers(headers_20))
    .pause(15 milliseconds)
    .exec(http("get folders")
    .get("""/workspace/folders?filter=owner&_=1384423227868""")
    .headers(headers_20))
    .exec(http("get shared folders")
    .get("""/workspace/folders?filter=shared&_=1384423227870""")
    .headers(headers_20))
    .pause(61 milliseconds)
    .exec(http("get root documents")
    .get("""/workspace/documents?hierarchical=true&filter=owner&_=1384423227873""")
    .headers(headers_20))
    .pause(43 milliseconds)
    .exec(http("original.css")
    .get("""/infra/public/css/original.css""")
    .headers(headers_120)
    .check(status.in(Seq(200, 304))))
    .pause(29 milliseconds)
    .exec(http("empty document avatar")
    .get("""/userbook/document/?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_46))
    .exec(http("get user theme")
    .get("""/theme?token=0.7430935838724188""")
    .headers(headers_26))
    .exec(http("get userbook infos")
    .get("""/userbook/api/person?_=1384423227874""")
    .headers(headers_20))
    .pause(14 milliseconds)
    .exec(http("get list-view template")
    .get("""/workspace/public/template/list-view.html""")
    .headers(headers_37))
    .pause(209 milliseconds)
    .exec(http("theme.css")
    .get("""/assets/themes/panda/panda-food/theme.css""")
    .headers(headers_123)
    .check(status.in(Seq(200, 304))))
    .pause(34 milliseconds)
    .exec(http("get icon avatar")
    .get("""/userbook/document/${meAvatar}?userbook-dimg=public/img/no-avatar.jpg&v=&thumbnail=48x48""")
    .headers(headers_133)
    .check(status.in(Seq(200, 304))))
    .pause(112 milliseconds)
    .exec(http("panda-food-background.jpg")
    .get("""/assets/themes/panda/img/illustrations/panda-food-background.jpg""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(11 milliseconds)
    .exec(http("shutdown.png")
    .get("""/assets/themes/panda/img/icons/shutdown.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/assets/themes/panda/img/illustrations/logo.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("add.png")
    .get("""/assets/themes/panda/img/icons/add.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("/user.png")
    .get("""/assets/themes/panda/img/icons/user.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(11 milliseconds)
    .exec(http("storage.png")
    .get("""/assets/themes/panda/img/icons/storage.png""")
    .headers(headers_38))
    .exec(http("show-icons.png")
    .get("""/assets/themes/panda/img/icons/show-icons.png""")
    .headers(headers_35))

  val chain_5 = exec(http("show-list-selected.png")
    .get("""/assets/themes/panda/img/icons/show-list-selected.png""")
    .headers(headers_38))
    .exec(http("KGJuneBug.ttf")
    .get("""/assets/themes/panda/fonts/KGJuneBug.ttf""")
    .headers(headers_131)
    .check(status.in(Seq(200, 304))))
    .pause(21 milliseconds)
    .exec(http("folder.png")
    .get("""/assets/themes/panda/img/icons/folder.png""")
    .headers(headers_46))
    .pause(11 milliseconds)
    .exec(http("img.png")
    .get("""/assets/themes/panda/img/icons/img.png""")
    .headers(headers_46))
    .pause(235 milliseconds)
    .exec(http("list visibles users for rack send")
    .get("""/workspace/users/available-rack?_=1384423227872""")
    .headers(headers_20))
    .pause(4)
    .exec(http("close-2x.png")
    .get("""/assets/themes/panda/img/icons/close-2x.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .exec(http("get create-file template")
    .get("""/workspace/public/template/create-file.html""")
    .headers(headers_37))
    .pause(9)
    .exec(http("loading.gif")
    .get("""/assets/themes/panda/img/illustrations/loading.gif""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(75 milliseconds)
    .exec(http("upload document")
    .post("""/workspace/document?thumbnail=120x120&name=6291049729_a5b5a3bdcc_o""")
    .headers(headers_337)
    .body(RawFileBody("TeacherSimulation_request_337.txt"))
    .check(status.is(201), jsonPath("$._id").find.saveAs("document0Id")))
    .pause(232 milliseconds)
    .exec(http("list root documents")
    .get("""/workspace/documents?hierarchical=true&filter=owner&_=1384423227875""")
    .headers(headers_20))
    .pause(5)
    .exec(http("get comment document template")
    .get("""/workspace/public/template/comment.html""")
    .headers(headers_37))
    .pause(19)
    .exec(http("add comment to document ${document0Id}")
    .post("""/workspace/document/${document0Id}/comment""")
    .headers(headers_188)
    .param("""comment""", """Une image de cupcakes."""))
    .pause(4)
    .exec(http("get share template")
    .get("""/workspace/public/template/share.html""")
    .headers(headers_37))
    .pause(19 milliseconds)
    .exec(http("get share-panel template")
    .get("""/infra/public/template/share-panel.html""")
    .headers(headers_342)
    .check(status.in(Seq(200, 304))))
    .pause(310 milliseconds)
    .exec(http("get share infos to document ${document0Id}")
    .get("""/workspace/share/json/${document0Id}?_=1384423227876""")
    .headers(headers_20))
    .pause(13)
    .exec(http("close.png")
    .get("""/assets/themes/panda/img/icons/close.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(1)
    .exec(http("checkbox-checked.png")
    .get("""/assets/themes/panda/img/icons/checkbox-checked.png""")
    .headers(headers_125)
    .check(status.in(Seq(200, 304))))
    .pause(19 milliseconds)
    .exec(http("share document to teachers (read)")
    .put("""/workspace/share/json/${document0Id}""")
    .bodyPart(StringBodyPart("""groupId""", """${profilGroupTeachersSchoolId}"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-workspace-service-WorkspaceService|getDocument""")))
    .pause(1)
    .exec(http("share document to teachers (comment)")
    .put("""/workspace/share/json/${document0Id}""")
    .bodyPart(StringBodyPart("""groupId""", """${profilGroupTeachersSchoolId}"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-workspace-service-WorkspaceService|commentDocument""")))
    .pause(1)
    .exec(http("share document to students (read)")
    .put("""/workspace/share/json/${document0Id}""")
    .bodyPart(StringBodyPart("""groupId""", """${profilGroupStudentsSchoolId}"""))
    .bodyPart(StringBodyPart("""actions""", """org-entcore-workspace-service-WorkspaceService|getDocument""")))
    .pause(11)
    .exec(http("logout")
    .get("""/auth/logout?callback=""")
    .headers(headers_1)
    .check(status.is(302)))
    .exec(http("get root page")
    .get("""/""")
    .headers(headers_1)
    .check(status.is(302)))
    .exec(http("get login page")
    .get("""/auth/login?callback=http://one/""")
    .headers(headers_1))
    .pause(24 milliseconds)
    .exec(http("auth.css")
    .get("""/auth/public/css/auth.css""")
    .headers(headers_351)
    .check(status.in(Seq(200, 304))))
    .exec(http("auth.js")
    .get("""/auth/public/js/auth.js""")
    .check(status.in(Seq(200, 304))))
    .exec(http("auth.png")
    .get("""/auth/public/img/auth.png""")
    .headers(headers_353)
    .check(status.in(Seq(200, 304))))
    .pause(33 milliseconds)
    .exec(http("KGJuneBug.ttf")
    .get("""/auth/public/fonts/KGJuneBug.ttf""")
    .headers(headers_354)
    .check(status.in(Seq(200, 304))))
    .exec(http("logo.png")
    .get("""/auth/public/img/illustrations/logo.png""")
    .headers(headers_353)
    .check(status.in(Seq(200, 304))))

  val scn = scenario("Teacher Scenario").exec(
    chain_0, chain_1, chain_2, chain_3, chain_4, chain_5)

}
