package org.entcore.broker.proxy;

import io.vertx.core.Future;
import org.entcore.broker.api.BrokerListener;
import org.entcore.broker.api.dto.BaseResponseDTO;

public interface AIWikiGeneratorListener {
    //TODO should be generated by cli(needed for json)
    //TODO use dummy dto to avoid issues

    @BrokerListener(
            subject = "ai.wiki.content.updated",
            proxy = true
    )
    Future<BaseResponseDTO> updateWikiContent(BaseResponseDTO content);

    @BrokerListener(
            subject = "ai.wiki.structure.updated",
            proxy = true
    )
    Future<BaseResponseDTO>  updateWikiStructure(BaseResponseDTO structure);
}
