GRANT USAGE ON SCHEMA audience TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA audience TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA audience TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA audience TO "apps";