#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

MODIFIED_FILES=$(git diff --cached --name-only)

if echo "$MODIFIED_FILES" | grep -q '^conversation/frontend'; then
  echo "🔍 Changes detected in the conversation module..."
  pnpm --filter conversation run pre-commit
fi