#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --name-only "$(git merge-base HEAD @{upstream})" HEAD | grep -q '^conversation/frontend'; then
  echo "🔍 Changes detected in the conversation module..."
  pnpm --filter conversation run pre-push
fi