<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.entcore</groupId>
        <artifactId>ent-core</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>workspace</artifactId>

    <properties>
        <lame4jVersion>2.1.0</lame4jVersion>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.entcore</groupId>
            <artifactId>common</artifactId>
            <version>${entCoreLibsVersion}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.entcore</groupId>
            <artifactId>session</artifactId>
            <version>${entCoreLibsVersion}</version>
            <scope>runtime</scope>
            <classifier>fat</classifier>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-web-client</artifactId>
            <version>${vertxVersion}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>de.maxhenkel.lame4j</groupId>
            <artifactId>lame4j</artifactId>
            <version>${lame4jVersion}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>fr.wseduc</groupId>
            <artifactId>mod-image-resizer</artifactId>
            <version>${imageResizerVersion}</version>
            <scope>runtime</scope>
            <classifier>fat</classifier>
        </dependency>
        <dependency>
            <groupId>org.entcore</groupId>
            <artifactId>test</artifactId>
            <version>${entCoreLibsVersion}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>henkelmax.public</id>
            <url>https://maven.maxhenkel.de/repository/public</url>
        </repository>
    </repositories>

</project>